# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-09 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetusbooks', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='avatar',
        ),
    ]
