# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetusbooks', '0005_auto_20170409_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/avatar.jpg', upload_to='avatar'),
        ),
    ]
