# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetusbooks', '0007_book_book_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_img',
            new_name='thumbnail',
        ),
    ]
