# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetusbooks', '0008_auto_20170410_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
