# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetusbooks', '0009_book_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
